### PR TITLE
Adding doze mode observation

### PR DESCRIPTION
**Pull request by aperfilyev**
#115 this is how I see it.

According to https://developer.android.com/training/monitoring-device-state/doze-standby.html#restrictions, network access is suspended in Doze mode.

### CODE REVIEW

**Comment by pwittchen** [comment]
Thank you for this PR! I'll review and test it as soon as I can.

**Comment by Kisty** [comment]
Can you rebase the PR on the master branch and push changes to your pr branch? I think the code coverage tool fails have been fixed with a recent commit.

**Comment by pwittchen** [comment]
@aperfilyev Can you squash your commits into one commit? You can use this website: http://rebaseandsqua.sh/. 

@Kisty codecov.io fails the PR because of decreased code coverage. Decreasing code coverage by 4% is not a big deal here and we can increase it later. I'm gonna add more "liberal" configuration for codecov.io, so it won't fail the PR if the drop of code coverage was very small.

**Comment by pwittchen** [comment]
After looking at the code and this PR, I think that creating a new strategy like `MarshmallowNetworkObservingStrategy` would be a good idea in the case of Doze mode. I haven't noticed that during the discussion in issue #115 and I wasn't aware of the fact that this feature is available since Android M. Nevertheless when you squash your commits, I can merge it and we can refactor it later quite easily, so finally we'll have 3 strategies for network monitoring.

**Comment by aperfilyev** [comment]
@pwittchen done.

**Pull request merged**
